# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/budget_tracker
spring.datasource.username=root
spring.datasource.password=Password123

# Hibernate ? auto-creates/updates tables based on your entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional but helpful ? formats the SQL logs
spring.jpa.properties.hibernate.format_sql=true

# App name
spring.application.name=budget-tracker

server.servlet.session.persistent=false